#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Apr 28 12:30:27 WEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=10
shaderPack=\u00A7r\u00A7lAstra\u00A74\u00A7lLex\u00A7r\u00A7l_By_LexBoosT_\u00A74\u00A7lV92.1\u00A7r\u00A7l.zip
