# Don't change this! Version used to track needed updates.
version = 1
disableParticles = false
byTypeReductions = {  }
maxParticlesPerSheet = 4000
particleRenderDistanceMultiplier = 0.5977090992647063
asynchronousTicking = false
cullingBlacklist = [  ]
cullingBehavior = "AGGRESSIVE"
reduceAllChance = 0.0
reduceDecreasedChance = 0.0
turnOffPotionParticlesV2 = [
    "NONE"
]