# Don't change this! Version used to track needed updates.
version = 0

[ambiance]
# The chance of hearing leaves blow with the wind (1 in x)
leavesIdleChance = 4000
# The chance of hearing additional sounds from trees (1 in x)
leavesAdditionsChance = 10000
# The chance of hearing robins chirp in the early morning (1 in x)
leavesDawnAdditionsChance = 20000
# The chance of hearing wolves howl at night (1 in x)
forestWolfChance = 100000
# Sets if the distant insect chirp loop sound should be played at night
enableNightIdle = true
# Sets if the river loop sound should be played
enableRiverSounds = true
# Sets if the swamp loop sounds should be played
enableSwampSounds = true
# Sets if the ocean loop sound should be played
enableOceanSounds = true
# Sets if the jungle loop sounds should be played
enableJungleIdle = true
# Sets if the plains and savanna ambient loop sound should be played
enablePlainsSavannaIdle = true
# Sets if the desert ambient loop sound should be played
enableDesertIdle = true
# The chance of hearing ambient village noises (1 in x)
villageAdditionsChance = 0

[weather]
# Enables the new, distance-based thunder sounds
newThunderSounds = true
# The maximum distance (in blocks) that the close thunder sound set will play at
closeThunderDistance = 90.0
# The maximum distance (in blocks) that the medium thunder sound set will play at
mediumThunderDistance = 140.0